### ISSUE TITLE
Doubling of titles

### ISSUE THREAD

**Issue by florianhartig** [biometry/APES#27]
At the moment, most documents have the title twice, once because it is automatically created from the document header, and one again in the document, see e.g. 

http://biometry.github.io/APES/Stats/stats01-DescriptiveStatistics.html

can you remove all titles from the Rmd and md documents. You can commit this, but I would not recompile the Rmd to avoid having all the pictures newly commited

**Comment by AndreaJO** [comment]
done

**Comment by florianhartig** [comment]
hey Andrea, sorry that I have to reopen this again, but you forgot to remove the === , those were part of the title, a title in md is

title
===

**Comment by AndreaJO** [comment]
Now they're (I hope) done

**Comment by florianhartig** [comment]
Thanks!
